---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: url-shortner
  namespace: flux-system
spec:
  interval: 3m
  path: chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: url-shortner
  targetNamespace: url-shortner

