# This rule is not used by the project mongo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to database.sadegh.msm resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodbcluster-viewer-role
rules:
- apiGroups:
  - database.sadegh.msm
  resources:
  - mongodbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.sadegh.msm
  resources:
  - mongodbclusters/status
  verbs:
  - get
