FROM docker:28-dind

RUN apk update && apk add --no-cache curl bash \
  && curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 \
  && chmod +x /usr/local/bin/gitlab-runner

RUN adduser -D -g '' gitlab-runner
