---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-database-sadegh-msm-v1alpha1-mongodbcluster
  failurePolicy: Fail
  name: mmongodbcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - database.sadegh.msm
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-sadegh-msm-v1alpha1-mongodbcluster
  failurePolicy: Fail
  name: vmongodbcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - database.sadegh.msm
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbclusters
  sideEffects: None
