---
- name: Install sudo
  package:
    name: sudo
    state: present
  tags: hardening

- name: Ensure user is in sudo group
  user:
    name: "{{ user_name }}"
    groups: sudo
    append: yes
  when: user_name is defined
  tags: hardening

- name: Enforce sudo and restrict su
  lineinfile:
    dest: /etc/pam.d/su
    regexp: '^#?auth\s+required\s+pam_wheel.so use_uid'
    line: 'auth required pam_wheel.so use_uid'
    state: present
  tags: hardening

- name: Ensure 'sudo' group is treated as 'wheel' group for su
  lineinfile:
    path: /etc/group
    regexp: '^sudo:'
    line: "{{ item }}"
  with_items:
    - "sudo:x:27:{{ user_name | default('ubuntu') }}"
  tags: hardening

- name: Configure sudoers for sudo group
  copy:
    dest: /etc/sudoers.d/90-custom-sudo
    content: |
      %sudo ALL=(ALL) ALL
    mode: '0440'
  tags: hardening

