---
- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash
  when: user_name is defined
  tags: passwordless

- name: Create .ssh directory
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: user_name is defined
  tags: passwordless

- name: Install public key for passwordless SSH
  ansible.builtin.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', public_key_file) }}"
    manage_dir: no
  when:
    - user_name is defined
  tags: passwordless
